backend/analysis/urls.py
from django.urls import path

from . import views

app_name = 'analysis'

urlpatterns = [
  path('', views.index, name='index'),
  ]

backend/backend/urls.py
from django.contrib import admin
from cuser.forms import AuthenticationForm
from django.urls import path, include
from django.contrib.auth.views import LoginView
from django.views.generic import TemplateView

from content import views


urlpatterns = [
    path('content/', include('content.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/login', LoginView.as_view(authentication_form=AuthenticationForm), name='login'),
    path('register/', views.register, name='register'),
    path('', views.home, name='home'),
    path('testarea/', views.test_area, name='test_area'),
    path('answers/', views.create_post, name='create_post'),
    # for the belts app
    path('belts/', include('belts.urls')),

    # for the analysis app
    path('analysis/', include('analysis.urls')),

    # for the user api
    path('', include('users.urls')),

    # for the userbelts api
    path('', include('belts.urlsapi')),

    # for the questions api
    path('', include('content.urlsapi')),

    # for the password reset
    path('api/password_reset/', include('django_rest_passwordreset.urls', namespace='password_reset')),

    # for analysis
    path('', include('data.analysis.urlsapi')),



]

backend/belts/urls.py
from django.urls import path

from . import views

app_name = 'belts'

urlpatterns = [
  path('', views.index, name='index'),

  ]

backend/content/urls.py
from django.urls import path
from . import views


app_name = 'content'
urlpatterns = [
  path('', views.index, name='index'),
  path('start/', views.starting_point, name='starting_point'),
  path('mybelts/', views.UserBeltPage.as_view(), name='my-belts'),
  path('start/myquestions/', views.MyQuestions.as_view(), name='my-questions'),


]

urlpatterns += [

]

backend/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

  <link href="https://fonts.googleapis.com/css?family=Dokdo" rel="stylesheet">
  {% block stylesheet %}{% endblock %}

</head>

<body>

<!-- Navigation bar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Smrtr.life</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

        {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'test_area' %}">TestArea</a></li>

            <li class="nav-item">
              <a class="nav-link disabled" href="#">User: {{ user.get_username }}</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'content:my-belts' %}">My Belts</a></li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'content:starting_point' %}">My Qs</a></li>

            <li><a class="nav-link" href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
        {% else %}
            <li><a class="nav-link" href="{% url 'login'%}?next={{request.path}}">Login</a></li>
        {% endif %}
    </ul>
  </div>
</nav>

<!-- block for content -->
<main>
{% block content %}
{% endblock %}
</main>

<!-- footer for all -->
      <footer>
        <br>
      <a href="{% url 'belts:index' %}">Belts App</a>
        <br>
      <a href="{% url 'analysis:index' %}">Analysis App</a>
        <br>
      <a href="{% url 'register' %}">Register</a>
        <br>
      <a href="{% url 'admin:index' %}">Admin Page</a>
      </footer>

<!-- jquery and javascript -->
  {% block js %}
    <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
  {% endblock %}
{% block extrajs %}
{% endblock %}

backend/templates/testarea.html
{% extends 'base.html' %}


{% block content %}

<p>⛩</p>



{% endblock %}